server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    username: ${POSTGRES_USERNAME:root}
    password: ${POSTGRES_PASSWORD:9qwe1ox}
    url: ${POSTGRES_AUTH_URL:jdbc:postgresql://localhost:5433/auth-service}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog.yml

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: false
        show_sql: false

  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:localhost}
      port: 8500
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true
        ip-address: ${SPRING_CLOUD_CONSUL_HOST_DISCOVERY_IP_ADDRESS:host.docker.internal}
      config:
        enabled: true
        format: YAML

  config:
    import: "optional:consul:"

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:myVerySecretKeyForJWTTokenSigningThisShouldBe256BitsLong}
  expiration: ${JWT_EXPIRATION:604800000} # 7 дней в миллисекундах

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus