services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul-server-v2
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: "agent -dev -client=0.0.0.0"
    networks:
      - guardex-network

  postgres:
    image: postgres:latest
    container_name: postgres-guardex
    hostname: postgres-guardex
    restart: always
    environment:
      POSTGRES_DB: postgres-guardex
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 9qwe1ox
    ports:
      - "5432:5432"
    networks:
      - guardex-network

networks:
  guardex-network:
    driver: bridge