server:
  port: 8082

spring:
  application:
    name: vpn-management-service

  datasource:
    username: ${POSTGRES_USERNAME:root}
    password: ${POSTGRES_PASSWORD:9qwe1ox}
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres-guardex}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: false
        show_sql: false
        default_schema: public

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog.yml
    default-schema: public

  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:localhost}
      port: 8500
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true
        ip-address: ${SPRING_CLOUD_CONSUL_HOST_DISCOVERY_IP_ADDRESS:host.docker.internal}
      config:
        enabled: true
        format: YAML
  config:
    import: "optional:consul:"

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:myVerySecretJWTKeyForVPNProject2024!@#$%^&*()_+}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds

# Application Configuration
app:
  user-management-service:
    url: ${USER_MANAGEMENT_SERVICE_URL:http://localhost:8081}

# Logging Configuration
logging:
  level:
    server.vpn.com.vpnmanagement: DEBUG
    org.springframework.security: INFO