---------------------------------------------
-- changeset trapper:002
-- comment create refresh_tokens
---------------------------------------------

CREATE TABLE IF NOT EXISTS refresh_tokens
(
    refresh_token_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    token            VARCHAR(255) NOT NULL UNIQUE,
    user_id          UUID         NOT NULL,
    expires_at       TIMESTAMPTZ  NOT NULL,
    created_at       TIMESTAMPTZ  NOT NULL,
    updated_at       TIMESTAMPTZ,
    is_revoked       BOOLEAN      NOT NULL DEFAULT FALSE,
    device_info      VARCHAR(500),
    ip_address       VARCHAR(45),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

-- Индексы
CREATE INDEX idx_refresh_token ON refresh_tokens (token);
CREATE INDEX idx_user_id ON refresh_tokens (user_id);
CREATE INDEX idx_expires_at ON refresh_tokens (expires_at);

---------------------------------------------
-- rollback drop table if exists refresh_tokens;
---------------------------------------------