server:
  port: 8081

spring:
  application:
    name: user-management-service

  datasource:
    username: ${POSTGRES_USERNAME:root}
    password: ${POSTGRES_PASSWORD:9qwe1ox}
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres-guardex}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: false
        show_sql: false
        default_schema: public

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog.yml
    default-schema: public

  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:localhost}
      port: 8500
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true
        ip-address: ${SPRING_CLOUD_CONSUL_HOST_DISCOVERY_IP_ADDRESS:host.docker.internal}
      config:
        enabled: true
        format: YAML
  config:
    import: "optional:consul:"

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:myVerySecretJWTKeyForVPNProject2024!@#$%^&*()_+}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:2592000000} # 30 days in milliseconds

# App Security Configuration
app:
  security:
    max-sessions-per-user: ${MAX_SESSIONS_PER_USER:5} # Максимальное количество активных сессий на пользователя

# Logging Configuration
logging:
  level:
    server.vpn.com.auth: DEBUG
    org.springframework.security: INFO