server:
  port: 8080

spring:
  application:
    name: api-gateway-service

  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:localhost}
      port: 8500
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true
        ip-address: ${SPRING_CLOUD_CONSUL_HOST_DISCOVERY_IP_ADDRESS:host.docker.internal}
      config:
        enabled: true
        format: YAML

  config:
    import: "optional:consul:"

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus